config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  resources :posts
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
  has_many_attached :images
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :galleries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:age])
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[ show edit update destroy ]

  # GET /galleries or /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1 or /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = current_user.galleries.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries or /galleries.json
  def create
    @gallery = current_user.galleries.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to gallery_url(@gallery), notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to gallery_url(@gallery), notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.require(:gallery).permit(:name, :user_id,images: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:nome, :desc, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/galleries/_form.html.erb
<%= form_with(model: gallery) do |form| %>
  <% if gallery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
        <% gallery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images,multiple: true %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/_gallery.html.erb
<div id="<%= dom_id gallery %>">
  <p>
    <strong>Name:</strong>
    <%= gallery.name %>
  </p>

  <p>
    <strong>Imagens:</strong>
    <% if gallery.images.attached? %>
      <% gallery.images.each do |image| %>
        <%= image_tag image %>
      <% end %>
    <% end %>
  </p>
</div>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Show this gallery", @gallery %> |
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Galleries</h1>
<div id="galleries">
  <% @galleries.each do |gallery| %>
    <%= render gallery %>
    <p>
      <%= link_to "Show this gallery", gallery %>
    </p>
  <% end %>
</div>

<%= link_to "New gallery", new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gallery %>

<div>
  <%= link_to "Edit this gallery", edit_gallery_path(@gallery) %> |
  <%= link_to "Back to galleries", galleries_path %>

  <%= button_to "Destroy this gallery", @gallery, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if current_user %>
          <div class="div-central-navbar">
            <div class="links"/>
              <%= link_to "Home",root_path ,class: "navbar-brand"%>
              <%= link_to "Posts",posts_path ,class: "navbar-brand"%>
              <%= link_to "Galeria",galleries_path ,class: "navbar-brand"%>
            </div>
            <div class="botoes">
              <li class="nav-item">
                <%= link_to "Sair", destroy_user_session_path, 'data-turbo-method': :delete ,class:"btn btn-danger" %>
              </li>
            </div>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Cadastrar", new_user_registration_path, class: "btn btn-info"%>
    
          </li>
          <li class="nav-item">
            <%= link_to "Logar", new_user_session_path, class: "btn btn-success" %>
          </li>
        <% end %>
        </div>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Querido Diario</h1>
<% if current_user %>
  <h1>Bem vindo <%= current_user.name  %> <%=current_user.age %></h1>
  <%= link_to "Sair", destroy_user_session_path, 'data-turbo-method': :delete  %>
<% else %>
  <h1>Você está deslogada</h1>
  <%= link_to "Cadastrar", new_user_registration_path%>
  <%= link_to "Logar", new_user_session_path%>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_field :desc %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Nome:</strong>
    <%= post.nome %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= post.desc %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>